name: Build and Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: starter_linux
          - os: windows-latest
            artifact_name: starter_windows.exe
          - os: macos-latest
            artifact_name: starter_macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Build executable
        run: dart compile exe ./bin/launcher_bootstrap.dart -o ./${{ matrix.artifact_name }}

      - name: Upload artifact (temporary storage)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Flatten artifacts directory (optional, for cleaner paths)
        run: |
          mkdir -p release_files
          find ./artifacts -type f -exec mv {} ./release_files/ \;

      - name: List files for verification
        run: ls -la ./release_files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: ./release_files/*
